// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ref struct {
	RepoName string
	RefName  string
	Type     string
	Hash     pgtype.Text
	Target   pgtype.Text
}

type Repository struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
}

type SchemaMigration struct {
	Version string
}
