// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateRepository(ctx context.Context, name string) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository, name)
	var i Repository
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, name, created_at FROM repositories ORDER BY name
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
