// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
}

type SchemaMigration struct {
	Version string
}
